apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
        app: ${PROJECT_NAME}
        tier: frontend
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}
        tier: frontend
    spec:
      containers:
      - name: guestbook
        image: gcr.io/${GOOGLE_PROJECT_ID}/${PROJECT_NAME}:${IMAGE_TAG}
        env:
        - name: GET_HOSTS_FROM
          value: "dns"
        - name: REDIS_URL
          value: ${REDIS_URL}
        - name: REDIS_PASSWORD
          value: ${REDIS_PASSWORD}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80